# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/StudyRepository/SystemDesignLab/Lab19/vivado/MusicPlayer.srcs/sources_1/ip/DCM_Audio/DCM_Audio.xci
# IP: The module: 'DCM_Audio' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/StudyRepository/SystemDesignLab/Lab19/vivado/MusicPlayer.srcs/sources_1/ip/DCM_Audio/DCM_Audio_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_Audio'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/StudyRepository/SystemDesignLab/Lab19/vivado/MusicPlayer.srcs/sources_1/ip/DCM_Audio/DCM_Audio.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_Audio'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/StudyRepository/SystemDesignLab/Lab19/vivado/MusicPlayer.srcs/sources_1/ip/DCM_Audio/DCM_Audio_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_Audio'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/StudyRepository/SystemDesignLab/Lab19/vivado/MusicPlayer.srcs/sources_1/ip/DCM_Audio/DCM_Audio.xci
# IP: The module: 'DCM_Audio' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/StudyRepository/SystemDesignLab/Lab19/vivado/MusicPlayer.srcs/sources_1/ip/DCM_Audio/DCM_Audio_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_Audio'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/StudyRepository/SystemDesignLab/Lab19/vivado/MusicPlayer.srcs/sources_1/ip/DCM_Audio/DCM_Audio.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_Audio'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/StudyRepository/SystemDesignLab/Lab19/vivado/MusicPlayer.srcs/sources_1/ip/DCM_Audio/DCM_Audio_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_Audio'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
